run_build_section_feature('/home/tzeng/ABA/autoGenelable_multi_lables_proj/temp/infor_exchange_finetune_vgg_16_multi_shared_weight_net_FirstLR_10-20_lastLR_4-8_TLR_1-E5_step500_blancedSample_ontoL_5_SLICE_ISH_iter_10000E11.5conv4_3ISH');
exit
